# Generated by Django 4.0 on 2021-12-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alternatives',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependencies', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='projects.project'),
        ),
    ]
