# Generated by Django 4.0 on 2021-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_alternatives_alter_project_depends_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
