# Generated by Django 4.0 on 2021-12-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['path__length', 'path']},
        ),
        migrations.AddField(
            model_name='project',
            name='depth',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(db_index=True, default='0', editable=False, max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_childs', to='projects.project'),
        ),
    ]
