# Generated by Django 4.0 on 2021-12-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0008_alter_project_options_project_depth_project_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='alternatives',
        ),
        migrations.AddField(
            model_name='project',
            name='alternatives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='projects.alternatives'),
        ),
    ]
