# Generated by Django 4.0 on 2021-12-21 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0009_alternatives_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alternatives',
            new_name='ConcurrencyGroup',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='alternatives',
            new_name='concurrency_group',
        ),
    ]
