# Generated by Django 4.0 on 2021-12-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0010_rename_alternatives_concurrencygroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
