# Generated by Django 4.0 on 2022-01-17 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20211130_1235'),
        ('projects', '0013_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate',
                                               to='users.user')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegator',
                                                to='users.user')),
                ('tags', models.ManyToManyField(to='projects.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
