# Generated by Django 4.0 on 2022-01-31 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0015_alter_delegation_delegate_alter_delegation_delegator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegation',
            old_name='tags',
            new_name='tag',
        ),
    ]
