# Generated by Django 4.0 on 2022-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0017_remove_delegation_unique delegation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delegation',
            name='unique delegation',
        ),
        migrations.AddConstraint(
            model_name='delegation',
            constraint=models.UniqueConstraint(fields=('delegator', 'tag'),
                                               name='unique delegation'),
        ),
    ]
