# Generated by Django 4.0 on 2022-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0018_remove_delegation_unique delegation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
