# Generated by Django 4.0 on 2022-02-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_alter_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="delegation",
            name="unique delegation",
        ),
        migrations.RemoveField(
            model_name="delegation",
            name="tag",
        ),
        migrations.AddField(
            model_name="delegation",
            name="theme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.theme",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="delegation",
            constraint=models.UniqueConstraint(
                fields=("delegator", "theme"), name="unique delegation"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.theme",
            ),
        ),
    ]
