# Generated by Django 4.0 on 2022-02-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_theme_remove_delegation_unique delegation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
