# Generated by Django 4.0 on 2022-02-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_project_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delegation',
            name='unique delegation',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='theme',
        ),
        migrations.AddField(
            model_name='delegation',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.tag'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='delegation',
            constraint=models.UniqueConstraint(fields=('delegator', 'tag'), name='unique delegation'),
        ),
    ]
