# Generated by Django 4.0 on 2022-02-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0023_remove_delegation_unique delegation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'project'),
                                               name='unique vote'),
        ),
    ]
