# Generated by Django 4.0 on 2022-02-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0024_vote_unique vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='vote',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
