# Generated by Django 4.0 on 2022-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0025_remove_vote_upvote_vote_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='upvote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='weight',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
