# Generated by Django 4.0 on 2022-02-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0026_vote_upvote_alter_vote_weight'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delegation',
            name='unique delegation',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='tag',
        ),
        migrations.AddField(
            model_name='delegation',
            name='theme',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='projects.theme'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='delegation',
            constraint=models.UniqueConstraint(fields=('delegator', 'theme'),
                                               name='unique delegation'),
        ),
    ]
