# Generated by Django 4.0 on 2022-02-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0020_alter_tag_name'),
        ('users', '0002_auto_20211130_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('tag',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='projects.tag')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='users.user')),
            ],
        ),
    ]
